### ISSUE TITLE
Attribuer à TotalAustral SA la parent company TotalEnergies

### ISSUE THREAD

**Issue by OrianeWgn** [dataforgoodfr/CarbonBombs#101]
Veiller à ce que chaque occurrence de TotalAustral SA soit associée à la parent company "TotalEnergies". Créer le lien à la main si besoin quand il n'existe pas sur GEM (ex. Vaca Muerta)

@Nathanlauga est-ce que tu penses que c'est possible la semaine pro par exemple ? C'est pas prio pour demain, on en rediscute de vive voix si tu veux

**Comment by louwelgryn** [comment]
pour préciser dans GEM Vaca muerta est attribuée à TotalAustral - on aimerait remplacer ce nom par total tout court pour que cette bombe soit attribuée à total ? est ce possible ?

**Comment by Nathanlauga** [comment]
Pour info le nom normalisé de TotalEnergies est le suivant : "TotalEnergies SE".
Il s'agit du nom utilisé dans BOCC.

Cela me permet également de rappeler que sur le fichier `carbon_bombs_informations.csv` les noms ne sont pas normalisés car ils sont composé de la valeur brute de GEM (ce qui n'a pas d'impact sur le site)

**Comment by louwelgryn** [comment]
pas sure d'avoir compris - il faudrait que l'entreprise TotalAustral soit remplacée par "TotalEnergies SE" du coup pour être reliée à total - sinon la elle est attribuée à totalAustral et cela amoindri le nombre de bombes de total. Tu vois ce que je veux dire ? 
Par ailleurs je pense du coup que c'est important qu'on prenne le même nom partout sinon ça créé des incohérences pour les gens qui utilisent la base de données. @Nathanlauga
