### ISSUE TITLE
Create a column GEM_project_name_source_GEM

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/CarbonBombs#104]
Kikouu
ca serait génial de pouvoir avoir une colonne qui s'appelle GEM_project_name_source_GEM qui a non pas les ids mais les Unit names ( de la colonne qu'on utilise pour le manual matching) parce que les ids ne parlent pas aux gens. 
tu pourras placer cette colonne à la suite de GEM_id_source_GEM ( et l'ajouter dans les métadatas) ? 
merci beaucoup 
@Nathanlauga

**Comment by Nathanlauga** [comment]
On peut renommer la colonne `Multiple_unit_concerned_source_GEM` et la compléter pour les projets ayant un seul unit.
Son comportement actuel correspond à ton besoin, mais laisse des valeurs nulles pour les cas où il n'y a qu'une seule unit.

**Comment by louwelgryn** [comment]
trop bien ca me semble parfait !
