### ISSUE TITLE
Status GEM - complexification de la règle

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/CarbonBombs#107]
Contexte : 
on se rend compte que la règle qu'on avait défini de minimum un seul projet operating pour que tout le projet soit en operating est un peu simpliste et envoie les mauvais messages ( parce que les projets non commencés sont plus faciles à arreter donc il faut pas dégouter les gens et leur pointer des projets non commencé auxquels s'attaquer) 

du coup on se demandait si on pouvait définir une règle un peu plus complexe avec des pourcentages et un threshold ? 
si + de 30% en nombre des projets sont operating - alors le projet est operating ? 
A dispo pour échanger dessus quand tu veux ( par exemple mercredi matin cf mon message sur slack ;) ) 
mille mercis !

**Comment by Nathanlauga** [comment]
C'est possible oui

**Comment by louwelgryn** [comment]
@Nathanlauga c'est bon tu as pu le faire ?

**Comment by louwelgryn** [comment]
@Nathanlauga tu peux mettre 10% au lieu de 30% ? :)
