### ISSUE TITLE
remontée d'une incohérence entre git et carte ? ;)

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/CarbonBombs#108]
Erreur remontée : 
"Il est dit dans Github que le Koweit a 3 bombs, en cherchant par pays on en trouve qu’une. (Greater Burgan)"

**Comment by mnicolleUTC** [comment]
Euh je ne suis pas sur de comprendre, j'ai 4 bombs au "Kuwait' (attention a l'orthographe, je dis ca pour le journaliste je sais bien que tu as copier coller ;))
- Central Arabian Onshore
- Greater Burgan
- Project Kuwait
- Khafji
Je t'avoue que je ne comprends pas trop ce retour. Je te laisse close si besoin sinon me donner des éléments en plus pour approfondir :)

**Comment by mnicolleUTC** [comment]
Oui pardon je n'avais pas vu au début que tu spécifiais l'incohérence avec la carte.
Côté Neo4j on est bon voir screenshot. 
![Capture d’écran 2023-09-22 à 10 12 08](https://github.com/dataforgoodfr/CarbonBombs/assets/68548924/1fb833d1-e3e4-4dd9-aec8-882864e80ae5)

![Capture d’écran 2023-09-22 à 10 13 36](https://github.com/dataforgoodfr/CarbonBombs/assets/68548924/f6ce210b-2b99-40dd-9bac-6b3141328738)


Honnêtement je me demande si il ne s'est pas trompé lors de son retour
