### ISSUE TITLE
Wrong GPS coordinates - Mero (Libra NW) 

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/CarbonBombs#109]
remontée journaliste : 

projet : Mero (Libra NW) -  Libra | 

Wrong GPS coordinates (in Amazonia, whereas it's offshore)

Possible de modifier pour mettre la bonne ??

**Comment by Nathanlauga** [comment]
On a pas les coordonnées sur le site de GEM : https://www.gem.wiki/Libra_Oil_Field_(Brazil)
La source des coordonnées est bien indiquée  : "Country CB"

Il nous faut donc les vrais coordonnées pour corrigés ça.

**Comment by mnicolleUTC** [comment]
Oui d'accord avec Nathan, pas de GPS alors on prends les coordonées du pays associés ici Amazonia. A renseigner spécifiquement dans le readme ou dans la FAQ du site ??? Exemple : Comment traiter vous les sites d'extraction ou vous ne disposez pas des coordonnées GPS ? --> On prends le pays.

**Comment by louwelgryn** [comment]
ok j'ajoute dans la liste faq :)

**Comment by mnicolleUTC** [comment]
Ajouté dans la FAQ - Closed
