### ISSUE TITLE
donnée à creuser - Area 1 LNG (T1&T2)

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/CarbonBombs#110]
Projet : 
Area 1 LNG (T1&T2) | 

retour : It's Oil&Gas, should be Gas
à creuser ?

**Comment by mnicolleUTC** [comment]
Salut @louwelgryn, 
Du coup pour moi ceci n'est pas un problème, en fait nous on a deux catégories dans le dataset : Coal ou Oil&Gas.
Mais dans la catégorie Oil&Gas on ne fait pas la distinction entre Oil&Gas, uniquement Oil ou uniquement Gas (>>> df["Fuel_type_source_CB"].unique() --> array(['Oil&Gas', 'Coal'], dtype=object). Ca pourrait être fait das le futur si on commence a regarder les reserves présentes (pour la pourcentage d'appartenance notamment). Je peux ouvrir une issue la dessus en Priorité plus tard si tu veux pour garder l'idée en tête. Pour l'instant je te propose de close celle-ci :)
