### ISSUE TITLE
Bug remonté par journaliste - manque total dans connexion carbon bombs

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/CarbonBombs#112]
connexion_carbonbombs_company et carbon_bombs_informations | Area-1 Future Phases | No parent company is listed for TotalEnergies
-- | -- | --

A creuser?

**Comment by Nathanlauga** [comment]
Comme précisé dans cette issue : https://github.com/dataforgoodfr/CarbonBombs/issues/101
Le nom est normalisé dans les fichiers de connexions (bank / CB) et dans le fichier company par rapport aux noms des entreprises trouvés dans BOCC. `TotalEnergies` a donc la valeur suivante : `TotalEnergies SE`
