### ISSUE TITLE
inconsistance statuts

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/CarbonBombs#124]
incosistence statuts:( pas le meme statut entre notre base et GEM site)
Carmichael Coal Project
Integrated Belpahar, Lakhanpur, Lilari Coal Mine

**Comment by Nathanlauga** [comment]
The GEM dataset for Coal project is from April (the latest version available). I think it was updated between April and today, this is why there are differences.

**Comment by Nathanlauga** [comment]
I was wrong, the file was updated this month. So we need to update the source.
Also, we need to update the README
