### ISSUE TITLE
Bug coordonnées des bombes chinoises au Mexique 

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/CarbonBombs#128]
![bugChine](https://github.com/dataforgoodfr/CarbonBombs/assets/35841420/216265af-0c36-4bdf-822a-4c6648f666cb)

@Nathanlauga je pense qu'uil y a un pb de coordonnées ?

<img width="441" alt="image" src="https://github.com/dataforgoodfr/CarbonBombs/assets/35841420/34e4a736-3b7f-4860-b1fc-4d4d9c0f43ed">
il y en a 6 dis moi si tu as besoin de la liste mais tu peux voir le petit paquet sur la carte

**Comment by Nathanlauga** [comment]
En effet il y a un problème pour ce cas là, j'ai fixé le problème. Et je vais mettre en place un check pour m'assurer du bon fonctionnement du fix.
