### ISSUE TITLE
Anadarko - mettre des coordonnées GPS manuellement

### ISSUE THREAD

**Issue by OrianeWgn** [dataforgoodfr/CarbonBombs#133]
Problème sur la shale Anadarko, qui contenait des projets GEM offshore qui ne correspondaient pas au bassin géologique.
Nous avons supprimé tous les opérateurs (parce que nous n'en étions pas sûrs).

Il faut changer les coordonnées manuelles pour mettre celles [de ce projet](https://www.gem.wiki/Haley_(Lwr._Wolfcamp-Penn_Cons.)_-_Anadarko_Oil_and_Gas_Asset_(Texas,_United_States)) : 

Coordinates: 31.7908, -103.4136 (exact)

**Comment by Nathanlauga** [comment]
Je réalise que nous n'utilisons pas l'onglet Lat/long du manual matching
Est-ce qu'il faut l'implémenter ? https://docs.google.com/spreadsheets/d/11A3fmBmDz4yKaMcRhU70WKFUXAdcNYV6CABaFFni7cs/edit#gid=973856496

Si c'est le cas, est-ce que tu peux rajouter les coordonnées avec le nom de la CB ? :)
