### ISSUE TITLE
Creation of description and start year columns in carbon_bombs informations

### ISSUE THREAD

**Issue by mnicolleUTC** [dataforgoodfr/CarbonBombs#32]
With Scrapping and pattern matching, try to scrap GEM database to create the two columns description and start year in carbon_bombs informations. If not possible with Data provided from ChatGPT (csv file sent by slack), add start year and description of each carbon bombs.

**Comment by gpenessot** [comment]
@mnicolleUTC je pense que le doc envoyé sur slack n'est pas le bon, il s'agit du fichier xlsx concaténé

**Comment by mnicolleUTC** [comment]
@gpenessot My bad, the right file is now upload on Slack :)
