### ISSUE TITLE
Handle Kuwait Saoudi Arabia case

### ISSUE THREAD

**Issue by mnicolleUTC** [dataforgoodfr/CarbonBombs#34]
For the carbon bombs with 2 country : " Kuwait Saoudi Arabia " 
Assign the country to one or the other.
Source the decision in README.md
Clean the process of handling double country when creating unique value of country in country_informations.csv 
Thanks a lot

**Comment by FVarlet** [comment]
Suggestion: Creation of a mapping file between CB countries and UN data countries, instead of the current dict within the code.

**Comment by mnicolleUTC** [comment]
I don't see right now what your are talking about but feel free to add any enhancements to code behaviour :)
