### ISSUE TITLE
Fix ConocoPhilips Bug

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/CarbonBombs#73]
Il semble que des carbon bombs associées à des entreprises soients disponibles sur le excel mais pas sur le Neo4j - par exemple pour ConocoPhilips - il n'y a que 3 carbon bombs sur le Neo4j alors que dans l'excel j'en ai beaucoup plus ! 
Ultra prio comme bug parce que c'est une des entreprises qui finance le plus de bombes 

https://www.carbonbombs.org/companies - sur ConocoPhilips pour voir les projets auxquels on a accès via neo4j.

**Comment by mnicolleUTC** [comment]
Après vérification avec toi, cette issue n'est plus d'actualité. On la close
