### ISSUE TITLE
Correction location of bombs chatGPT

### ISSUE THREAD

**Issue by mnicolleUTC** [dataforgoodfr/CarbonBombs#81]
—> modifier manuellement le fichier chatGPT des coordonnées pour corriger les GPS qui nous ont été remontés. 

Ku-Maloob-Zaap Project - trouvé par chatGPT à corriger.
Gulf Deepwater Offshore - trouvé par chatGPT à corriger
Location of Santos Offshore - trouvé par chatGPT à corriger
--> et mettre un gros disclaimer dans le readMe que chatgpt quand pas dans GEM

--> KK propose de mettre quelques bénévoles pour regarder à la main ;) on est chauds

**Comment by Nathanlauga** [comment]
Done in https://github.com/dataforgoodfr/CarbonBombs/pull/98
