### ISSUE TITLE
Problem or bug on Carbon_bomb_description_source column 

### ISSUE THREAD

**Issue by mnicolleUTC** [dataforgoodfr/CarbonBombs#82]
In the data_cleaned output file the column Carbon_bomb_description_source is always equal to GEM. 
This seems impossible to I think there a big problem when fulfilling this column. 
Need to be investigated as soon as possible

**Comment by louwelgryn** [comment]
@mnicolleUTC je venais de m'en rendre compte en ouvrant le fichier ! je pense que c'est P1 ;)

**Comment by mnicolleUTC** [comment]
Yes c'est ce qu'on avait investigué avec Oriane, Top d'avoir ajouter P1, je pense que je me l'assign vu que l'on a dit avec Nathan que je gerais la partie ChatGPT

**Comment by mnicolleUTC** [comment]
Linked to #83

**Comment by mnicolleUTC** [comment]
Fixed with commit e78876027ab9ef7b5d442ee0139a5a730661fa73 and 9a1d1fe4f43d276994cb1b6f4b1a1d216201a9af
