### ISSUE TITLE
Revérification des manual matchiing

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/CarbonBombs#85]
C'est l'une des seules étapes ou l'on intervient et elle est cruciale car c'est à ce moment la qu'on attribue les projets aux entreprises et donc qu'on a une responsabilité ! 
Oriane et Lou relisent tout le manual matching ici : https://github.com/dataforgoodfr/CarbonBombs/blob/main/data_sources/manual_match.py
et justifient leurs choix de matching dans ce doc s'il y a des changements à faire https://docs.google.com/spreadsheets/d/11A3fmBmDz4yKaMcRhU70WKFUXAdcNYV6CABaFFni7cs/edit?pli=1#gid=518298211

Aprroche conservatrice : quand on ne sait pas, on ne matche pas

**Comment by louwelgryn** [comment]
notamment le cas de northfield doit être traité la dedans.

**Comment by mnicolleUTC** [comment]
Au vu des différentes conversations avec KK, important de porter une attention plus particulière au projet qui contiennent Shale OffShore ou Inshore car en soit pour rappel c'est un peu la catégorie fourre tout de Rystad lorsqu'il ne savent pas comment réunir des projets. Donc potentiellement le plus conservatif c'est de ne pas faire d'association (de manual match) sur ce type de projet car on arrivera jamais a reconstituer facilement et de manière exhaustive cette catégorie fourre tout. Après on perd peut etre trop d'infos A discuter.

**Comment by Nathanlauga** [comment]
Done in https://github.com/dataforgoodfr/CarbonBombs/pull/98
