### ISSUE TITLE
Création d'un onglets métadatas dans l'excels

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/CarbonBombs#88]
avec en colonne : 
- tabName : Nom du tab d'ou provient la colonne documentée
- columnName: nom de la colonne
- columnDescription : explication sur à quoi correspond à la donnée et comment elle est calculée
- unit : donne l'unité si numérique.

**Comment by Nathanlauga** [comment]
Done in https://github.com/dataforgoodfr/CarbonBombs/pull/98
