### ISSUE TITLE
Corriger les arrondis dans l'onglet carbon_bombs_information

### ISSUE THREAD

**Issue by louwelgryn** [dataforgoodfr/CarbonBombs#89]
Certains pourcentage ne sont pas arrondis à la décimale : 14.285714285714286%   dans l'onglet carbon_bombs_information
il faudrait arrondir à deux chiffres après la virgule.

**Comment by Nathanlauga** [comment]
Linked to https://github.com/dataforgoodfr/CarbonBombs/issues/86
